module.exports = {
  pubIDKey: 'pubID',
  pubNameKey: 'pubName',
  apiKeyKey: 'apiKey',
  reviewsFeedKey: 'reviewsFeed',
  payoutRateKey: 'payoutRate',
  updateFrequencyKey: 'updateFrequency',
  firstMonthsKey: 'firstMonth',
  currentMonthsKey: 'curMonth',
  lastRefreshKey: 'lastRefresh',
  salesSortOrderKey: 'salesSortOrder',
  salesInfoKey: 'salesInfo',
  reviewCountKey: 'reviewCount',
  sidebarTransitionKey: 'sidebarTransition',
  openAsPopupKey: 'openAsPopup',
  popupWindowWidthKey: 'popupWindowWidth',
  popupWindowHeightKey: 'popupWindowHeight',
  popupWindowTopPosKey: 'popupWindowTopPos',
  popupWindowLeftPosKey: 'popupWindowLeftPos'
}